[package]
license = ["Apache-2.0"]
keywords = ["api2pdf", "pdf", "convert", "web pages", "merge"]
org = "ballerinax"
name = "api2pdf"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true