[package]
license = ["Apache-2.0"]
keywords = ["Jira", "Projects", "Issues"]
org = "ballerinax"
name = "jira"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
